#!/bin/bash

#DEPLOY SCRIPT - should be placed in VC only. Replace omar dir and file names where necessary

BACKUP_PATH=/home/omar/Desktop/backups
INI_CONFIG=/home/omar/Desktop/Final/INI.config

#Filename
if [ -z "$1" ]; then
	echo "Enter filename to send:"
	read filename
else 
	filename=$1
fi

#Enter IP Address 
if [ -z "$2" ]; then
	echo "Enter Stage-Tier: "
	read ipIN
fi 

#IP ADDRESS ALIASES--------------------------------#

case $ipIN in
FE-DEV)
    ip=192.168.15.7
    name="omar"
    ;;
FE-QA)
    ip=192.168.15.6
    name="omar" 
    ;;
FE-PROD)
    ip=192.168.15.8
    name="omar"
    ;;
DB1-DEV)
    ip=192.168.15.20
    name="anwarrs"
    ;;
DB1-QA)
    ip=192.168.15.24
    name="anwarrs"
    ;;
DB1-PROD)
    ip=192.168.15.19
    name="anwarrs"
    ;;
#DB2-DEV)
#    ip=192.168.15.7
#    name="anwarrs"
#    ;;
#DB2-QA)
#    ip=192.168.15.7
#    name="anwarrs"
#    ;;
#DB2-PROD)
#    ip=192.168.15.7
#    name="anwarrs"
#    ;;
BE-DEV)
    ip=192.168.15.16
    name="hunter"
    ;;
BE-QA)
    ip=192.168.15.21
    name="hunter"
    ;;
BE-PROD)
    ip=192.168.15.22
    name="hunter"
    ;;
RMQ-DEV)
    ip=192.168.15.10
    name="nouman"
    ;;
RMQ-QA)
    ip=192.168.15.25
    name="nouman"
    ;;
RMQ-PROD)
    ip=192.168.15.26
    name="nouman"
    ;;
VC)
    ip=192.168.15.23
    name="hunter"
    ;;
TEST)
    ip=192.168.15.12
    name="omar"
    ;;
 *) #default
    printf "\n No valid stage-tier given. Exiting... \n"
    exit
    ;;
esac
#-----------------------------------------------#

printf "\n"

#PHP Code to CHMOD
if [ -z "$3" ]; then
       	echo "Enter php folder to chmod: "
	read phpFilepath #IT490/IT-490
else 
	phpFilepath=$3
fi

#Change file name based on if statement

if [[ $ipIN == *DEV ]]; then
	#run function to change ip in config file lines
elif [[ $ipIN == *QA ]]; then
	#run function to change ip in config file lines
elif [[ $ipIN == *PROD ]]; then
	#run function to change ip in config file lines
else
	printf "FAAAAAAAAAAAAAK >:(\n"
	exit
fi

#Print user of SSH
sshpass -p " " ssh $name@$ip bash -c "whoami"

#Copy and Backup version already on system
sshpass -p " " ssh $name@$ip bash -c "'tar cvpzf /home/$name/Desktop/backups/BACKUP.tar.gz $phpFilepath; exit'"

printf "\n-\n"

#Send zip to other computer desktop (If backup is already there, don't send it)
sshpass -p " " rsync -avzh $BACKUP_PATH/$filename $name@$ip:/home/$name --ignore-existing

printf "\n---\n"

#Extract zip, overwrite old files and Chmod php files (-C extracts to specific directory)"
sshpass -p " " ssh $name@$ip bash -c "'tar xvzf /home/$name/$filename -C /; cd $phpFilepath; chmod 755 *; exit'"

#For each line in config, sed it to replace the ip


printf "\n-----\n"

echo Version Pushed to $ip!;
