#!/bin/bash

PROJECT='/home/hunter/Desktop/testdir' #Please put the path to your PROJECT folder here
STAGE='testVM' #Please put your Folder name in VC here

#Prompt with warning
echo WARNING: This will delete all code within $PROJECT and replace it with the contents of $BACKUP_PATH/BACKUP.tar.gz. Are you ok with this? \(y/n\)
read conf

if [ "$conf" != "y" ]; then

	printf "\nK cool. Bye.\n"
	exit
fi
#Delete project
rm -rv $PROJECT/*

sshpass -p ' ' ssh hunter@192.168.15.23 hostname;cd;cd /home/hunter/Desktop/backups/$STAGE;sed -i '$ d' version.config;touch rollback2.txt;tail -n 1 version.config > rollback2.txt;


#Extract backup to Folder
#tar xvzf $BACKUP_PATH -C /

sshpass -p ' ' scp hunter@192.168.15.23:/home/hunter/Desktop/backups/$STAGE/rollback2.txt .
var=`tail -n 1 rollback2.txt`
sshpass -p ' ' scp hunter@192.168.15.23:/home/hunter/Desktop/backups/$STAGE/$var $PROJECT

rm rollback2.txt

#Extract backup to Folder
tar xvzf $PROJECT/$var -C $PROJECT

printf "\n Rolled version backup successfully!\n"
printf "\n\n"
