#!/bin/bash

PROJECT='/var/www/html/test' #Please put the path to your PROJECT folder here
STAGE='frontEnd' #Please put your Folder name in VC here

#Prompt with warning
echo WARNING: This will delete all code within $PROJECT and replace it with the contents of $BACKUP_PATH/BACKUP.tar.gz. Are you ok with this? \(y/n\)
read conf

if [ "$conf" != "y" ]; then

	printf "\nK cool. Bye.\n"
	exit
fi
#Delete project
rm -rv $PROJECT/*

#CD to folder, erase last ine of version.config, Get last version name
sshpass -p ' ' ssh hunter@192.168.15.23 bash -c "whoami;cd /home/hunter/Desktop/backups/$STAGE;pwd;sed -i '$ d' version.config;touch rollback2.txt;tail -n 1 version.config > rollback2.txt;"

#Extract backup to Folder
#tar xvzf $BACKUP_PATH -C /
echo "Done with SSH"
sshpass -p ' ' scp hunter@192.168.15.23:/home/hunter/Desktop/backups/$STAGE/rollback2.txt .
var=`tail -n 1 rollback2.txt`
sshpass -p ' ' scp hunter@192.168.15.23:/home/hunter/Desktop/backups/$STAGE/$var $PROJECT

rm rollback2.txt

#Extract backup to Folder
tar xvzf $PROJECT/$var -C $PROJECT

printf "\n Rolled version backup successfully!\n"
printf "\n\n"
