#!/bin/bash

PROJECT='/home/hunter/Desktop/testdir' #Please put the path to your PROJECT folder here
BACKUP='testVM' #Please put your Folder name in VC here

#Prompt with warning
echo WARNING: This will delete all code within $PROJECT and replace it with the contents of $BACKUP_PATH/BACKUP.tar.gz. Are you ok with this? \(y/n\)
read conf

if [ "$conf" != "y" ]; then

	printf "\nK cool. Bye.\n"
	exit
fi
#Delete project
#rm -r $PATH/*

sshpass -p ' ' ssh hunter@10.0.3.15 -t export "$BACKUP"; bash << EOF
cd
cd /home/hunter/Desktop/backups/$BACKUP
sed -i '$ d' version.config
touch rollback2.txt
tail -n 1 version.config > rollback2.txt
exit
EOF
#Extract backup to Folder
#tar xvzf $BACKUP_PATH -C /
#sshpass -p " " ssh $name@$ip bash -c "whoami"

sshpass -p ' ' scp hunter@10.0.3.15:/home/hunter/Desktop/backups/$BACKUP/rollback2.txt .
var=`tail -n 1 rollback2.txt`
sshpass -p ' ' scp hunter@10.0.3.15:/home/hunter/Desktop/backups/$BACKUP/$var $PROJECT

rm rollback2.txt

printf "\n Rolled version backup successfully!\n"
printf "\n\n"
