#!/bin/bash

#VC SCRIPT - Push zip file specified to VC

BACKUP_PATH=/home/omar/Desktop/backups
STAGE=frontEnd #Can be either frontEnd, backEnd, database, or rabbitMQ (case sensitive)

#Filename
if [ -z "$1" ]; then
	echo "Enter filename to send:"
	read filename
else 
	filename=$1
fi

#Enter IP Address 
ip=192.168.15.23
name="hunter"

#-----------------------------------------------#

printf "\n"

sshpass -p " " ssh $name@$ip bash -c "whoami"

#Send zip to other computer desktop (If backup is already there, don't send it)
sshpass -p " " rsync -avzh $BACKUP_PATH/$filename $name@$ip:/home/$name/Desktop/backups/$STAGE --ignore-existing

s='/version.config/d'
sshpass -p " " ssh $name@$ip bash -c "'cd /home/$name/Desktop/backups/$STAGE; ls -1tr > version.config;sed -i '/version.config/d' version.config;cat version.config; exit'"

printf "\n---\n"

echo Version Pushed to VC!!;
