#!/bin/bash

#tar cvpzf /home/omar/Desktop/backups/test.tar.gz /var/www/html/test 

PROJECT='/var/www/html/IT490'
BACKUP_PATH='/home/omar/Desktop/backups'
VERSION=IT-490-$(date +%s)

#Make backup folder if not there
if [!-d $BACKUP_PATH] 
then
	mkdir -p $BACKUP_PATH
	chmod +rw $BACKUP_PATH
fi #fi = end if

printf "\n" 

#zip version commit (-create-verbose-print-zip-filename)
exclude=$(</home/omar/Desktop/Final/EXCLUDE.config) #load exclude file
#echo $exclude

tar cvpzf $BACKUP_PATH/$(date -I)-$VERSION.tar.gz $exclude $PROJECT #zip all files except excluded ones.
#echo tar cvpzf $BACKUP_PATH/$(date -I)-$VERSION.tar.gz $value $PROJECT

#Finished!
printf "\n Created version successfully!\n"
printf "$BACKUP_PATH/\n$(date -I)-$VERSION.tar.gz\n\n"
