#!/bin/bash

#tar cvpzf /home/omar/Desktop/backups/test.tar.gz /var/www/html/test 

PROJECT='/var/www/html/test'
BACKUP_PATH='/home/omar/Desktop/backups'
VERSION=TEST-$(date +%s)

#Make backup folder if not there
if [!-d $BACKUP_PATH] 
then
	mkdir -p $BACKUP_PATH
	chmod +rw $BACKUP_PATH
fi #fi = end if

printf "\n" 

#Exclude files that are specified in EXCLUDE.config (no longer necessary -_-)
exclude=$(<./EXCLUDE.config) #load exclude file

#Zip version using tar (-create-verbose-print-zip-filename)
tar cvpzf $BACKUP_PATH/$(date -I)-$VERSION.tar.gz $exclude $PROJECT
#echo tar cvpzf $BACKUP_PATH/$(date -I)-$VERSION.tar.gz $value $PROJECT

#Finished!
printf "\n Created version successfully!\n"
printf "$BACKUP_PATH/\n$(date -I)-$VERSION.tar.gz\n\n"
